# Generated by Django 3.1.2 on 2020-11-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaulier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.TextField(max_length=200),
        ),
    ]
