# Generated by Django 3.1.2 on 2020-11-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaulier', '0002_auto_20201115_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='albumProducto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='artistaProducto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(default=0),
        ),
    ]
