# Generated by Django 3.1.2 on 2020-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaulier', '0003_auto_20201115_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='albumProducto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='artistaProducto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.CharField(max_length=15),
        ),
    ]
